export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_BODY = 'INVALID_BODY',
  INVALID_QUERY = 'INVALID_QUERY',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
}
